tienda/urls.py
from django.urls import path 
from .views import AgregarAutor, Inicio, Nosotros,  Login, contactoList, productos, Registro, contacto, AgregarLibro, libroList, fantasia, RomanceClasico, modificarLibro, eliminarLibro,  registro, carrito



urlpatterns = [
    path('Inicio/', Inicio, name='Inicio'), 
    path('Nosotros/', Nosotros, name='Nosotros'),
    path('Login/', Login, name='Login'), 
    path('productos/', productos, name='productos'), 
    path('Registro/', Registro, name='Registro'), 
    path('contacto/', contacto, name='contacto'), 
    path('agregar-libro/', AgregarLibro, name='agregar'), 
    path('libroList/', libroList, name='libroList'), 
    path('fantasia/', fantasia, name='fantasia'), 
    path('RomanceClasico/', RomanceClasico, name='RomanceClasico'), 
    path('modificarLibro/<int:id>/', modificarLibro, name='modificarLibro'),

    path('eliminarLibro/<id>/', eliminarLibro, name='eliminarLibro'), 
    path('registro/', registro, name='registro'), 
    path('carrito/', carrito, name='carrito'),
    path('agregar-Autor/', AgregarAutor, name='agregarAutor'), 
    path('contactoList/', contactoList, name='contactoList'), 






]

tienda/models.py
from collections import UserList
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Autor(models.Model):
    idAutor = models.IntegerField()
    nombre = models.CharField(max_length=100)

    def __str__(selft):
        return selft.nombre
    
opciones_categoria = [
    [0, "Romance"],
    [1, "Fantasia"],
    [2, "Romance Clasico"]
]
    
class Libro(models.Model):
    isbn = models.IntegerField()
    nombre = models.CharField(max_length=400)
    precio = models.IntegerField()
    categoria = models.IntegerField(choices=opciones_categoria)
    nuevo = models.BooleanField()
    autor = models.ForeignKey(Autor, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="Libros",null=True)

    def __str__(selft):
        return selft.nombre
    

tipoConsulta = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencia"],
    [3, "Felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=30)
    correo = models.EmailField()
    tipoConsulta = models.IntegerField(choices=tipoConsulta)
    mensaje = models.TextField()
    
    def __str__(selft):
        return selft.nombre
    




##modelo del carrito
class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    elementos = models.ManyToManyField(Libro, through='ElementoCarrito')

    def __str__(self):
        return f"Carrito de {self.usuario.username}"    
    



class ElementoCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Libro, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Elemento del carrito {self.carrito} - Producto: {self.producto} - Cantidad: {self.cantidad}"
    
    
    def subtotal(self):
        return self.producto.precio * self.cantidad
    

tienda/templates/tienda/Inicio.html
{%extends 'tienda/base.html'%}

{% block contenido1 %}

{% load static %}
<body>
		
	<!-- NUEVA FUNCION  -->
	<main>
		<div class="contenedor-img">
			 <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJWcTBTI49glVmEILZkcMrY0rTgkd-BgdMSw&usqp=CAU" alt="">
		</div>
		<div class="contenedor-texto">
			 <!-- Forma #1 -->
			 <h2 class="titulo">Descubre tus diferentes gustos <br> en <span class="typed"></span></h2>
			 <div class="botones">
				<a href="Registro.html" class="btn-link activo">Registrate</a>
				<a href="{% url 'contacto' %}" class="btn-link">Contacto</a>

			 </div>
			 
		</div>
   </main>
	<section class="container container-features">
		<div class="card-feature">
			<i class="fa-solid fa-plane-up"></i>
			<div class="feature-content">
				<span>Envío gratuito a nivel mundial</span>
				<p>En pedido superior a $100.000</p>
			</div>
		</div>
		<div class="card-feature">
			<i class="fa-solid fa-wallet"></i>
			<div class="feature-content">
				<span>Contrareembolso</span>
				<p>100% garantía de devolución de dinero</p>
			</div>
		</div>
		<div class="card-feature">
			<i class="fa-solid fa-gift"></i>
			<div class="feature-content">
				<span>Tarjeta regalo especial</span>
				<p>Ofrece bonos especiales con regalo</p>
			</div>
		</div>
		<div class="card-feature">
			<i class="fa-solid fa-headset"></i>
			<div class="feature-content">
				<span>Servicio al cliente 24/7</span>
				<p>LLámenos 24/7 al 123-456-7890</p>
			</div>
		</div>
	</section>
	<!-- tarjetas -->
	
		<div class="container-card">
			
			<div class="card">
				<figure>
					<img src="{% static 'images/romance.jfif'%}">
				</figure>
				<div class="contenido-card">
					<h3>Romance</h3>
					<p>Conservar algo que me ayude a recordarte sería admitir que te puedo olvidar. 'Romeo y Julieta', de William Shakespeare.</p>
					<a href="{% url 'productos' %}">Leer Màs</a>
				</div>
			</div>

			<div class="card">
				<figure>
					<img src="{% static 'images/fantasia.jfif'%}">
				</figure>
				<div class="contenido-card">
					<h3>Fantasia</h3>
					<p>¿Cómo retomas el hilo de una vida vieja? ¿Cómo continúas, cuando en tu corazón empiezas a entender que no hay regreso posible? (El señor de los anillos, de J.R.R. Tolkien).</p>
					<a href="{% url 'productos' %}">Leer Màs</a>
				</div>
			</div>

			<div class="card">
				<figure>
					<img src="{% static 'images/literatura.jfif'%}">
				</figure>
				<div class="contenido-card">
					<h3>Romance Clasicos</h3>
					<p>Aún entre los demonios hay unos peores que otros, y entre muchos malos hombres suele haber alguno bueno. (Don Quijote de la Mancha, de Cervantes)</p>
					
					<a href="{% url 'productos' %}">Leer Màs</a>
				</div>
			</div>
		</div>
<!--Fin   Tarjetas-->

	<section class="gallery">
		<img
			src="{% static 'images/1d.jfif'%}"
			alt="Gallery Img1"
			class="gallery-img-1"
		/><img
			src="{% static 'images/2d.png'%}"
			alt="Gallery Img2"
			class="gallery-img-2"
		/><img
			src="{% static 'images/cd.jfif'%}"
			alt="Gallery Img3"
			class="gallery-img-3"
		/><img
			src="{% static 'images/4d.jfif'%}"
			alt="Gallery Img4"
			class="gallery-img-4"
		/><img
			src="{% static 'images/cd2.jfif'%}"
			alt="Gallery Img5"
			class="gallery-img-5"
		/>
	</section>
	<!-- Productos LIBROS -->

	

{% load humanize %}
    <!-- productos -->
    <div class="produ">
      {% for p in libros %}
        <div class="card" style="width: 23rem;">
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="">
            {% endif %}
            <div class="card-body">
              <h5>{{p.autor | capfirst}}</h5>
              <h2 class="card-title">{{p.nombre | title}}</h2>
              <h3>${{p.precio | intcomma}}
              </h3>

              <a href="{% url 'Add' producto_id=p.id %}" class="btn btn-primary">Comprar</a>




            </div>
        </div>
        {% endfor %}
    </div>

	

<footer class="footer">
	<div class="container container-footer">
		<div class="menu-footer">
			<div class="contact-info">
				<p class="title-footer">Información de Contacto</p>
				<ul>
					<li>
						Dirección: 222 Viña del Mar, Chile 
					</li>
					<li>Teléfono: 33 747474</li>
					<li>Celular: 55555300</li>
					<li>EmaiL: Librosj&@gmail.com</li>
				</ul>
				<div class="social-icons">
					<span class="facebook">
						<i class="fa-brands fa-facebook-f"></i>
					</span>
					<span class="twitter">
						<i class="fa-brands fa-twitter"></i>
					</span>
					<span class="youtube">
						<i class="fa-brands fa-youtube"></i>
					</span>
					<span class="pinterest">
						<i class="fa-brands fa-pinterest-p"></i>
					</span>
					<span class="instagram">
						<i class="fa-brands fa-instagram"></i>
					</span>
				</div>
			</div>

			<div class="information">
				<p class="title-footer">Información</p>
				<ul>
					<li><a href="#">Acerca de Nosotros</a></li>
					<li><a href="#">Información Delivery</a></li>
					<li><a href="#">Politicas de Privacidad</a></li>
					<li><a href="#">Términos y condiciones</a></li>
					<li><a href="#">Contactános</a></li>
				</ul>
			</div>

			<div class="my-account">
				<p class="title-footer">Mi cuenta</p>

				<ul>
					<li><a href="#">Mi cuenta</a></li>
					<li><a href="#">Historial de ordenes</a></li>
					<li><a href="#">Lista de deseos</a></li>
					<li><a href="#">Boletín</a></li>
					<li><a href="#">Reembolsos</a></li>
				</ul>
			</div>

			<div class="newsletter">
				<p class="title-footer">Boletín informativo</p>

				<div class="content">
					<p>
						Suscríbete a nuestros boletines ahora y mantente al
						día con nuevas colecciones y ofertas exclusivas.
					</p>
					<input type="email" placeholder="Ingresa el correo aquí...">
					<button>Registrate</button>
				</div>
			</div>
		</div>

		<div class="copyright">
			<p>
				Desarrollado J&C &copy; 2023
			</p>

			<img src="{% static 'images/payment.png'%}" alt="Pagos"> 
		</div>

	</div>


{% endblock %}


	

tienda/templates/tienda/RomanceClasico.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" >
		<link rel="stylesheet" href="{% static 'css/productos.css'%}"/>
		<link rel="stylesheet" href="{% static 'css/nav.css'%}">
		
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	  

    <title>Romance clasico</title>
</head>
<body>
    <!-- NAV y HEADER -->
    <header>
			<div class="container-hero" >
				<div class="container hero">
					<div class="customer-support">
						<i class="fa-solid fa-headset"></i>
						<div class="content-customer-support">
							<span class="text">Soporte al cliente</span>
							<span class="number">123-456-7890</span>
						</div>
					</div>

					<div class="container-logo">
						<i class="books"></i>
						<h1 class="logo"><a href="#" > <img src="{% static 'images/LOGO (4).svg'%}" alt="" width="80" height="80"> </a></h1>
					</div>

					<div class="container-user">
						<a href="{% url 'Login' %}"><i class="fa-solid fa-user"></i></a>
						<a href="{% url 'carrito' %}"><i class="fa-solid fa-basket-shopping"></i></a>
						<div class="content-shopping-cart">
							<span class="link-carrito"></a> </span>
							<span class="number">(0)</span>
						</div>
					</div>
				</div>
			</div>
		</header>
			<!-- fin del header -->


			<!--aqui comienza el nav-->
			<section class="nav-total">
			<ul class="nav nav-tabs" style="justify-content:center;">
				<li class="nav-item">
				<a class="nav-link"  style="color: black;"  aria-current="page" href="{% url 'Inicio' %}">Inicio</a>
				</li>
				
				
				<li class="nav-item">
				<a class="nav-link" style="color: black;" href="{% url 'Nosotros' %}">Nosotros</a>
				</li>
				
				{% if perms.tienda.add_libro %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color: black;" data-bs-toggle="dropdown" href="{% url 'productos' %}" role="button" aria-expanded="true">Administracion</a>
					<ul class="dropdown-menu">
						{% if perms.tienda.add_libro %}
						<li class="nav-item">
							<a class="nav-link" style="color: black;" href="{% url 'agregar' %}">Agregar</a>
						</li>
						{% endif %}
						<li><hr class="dropdown-divider"></li>
						{% if perms.tienda.view_libro %}
						<li class="nav-item">
						<a class="nav-link" style="color: black;" href="{% url 'libroList' %}">Listar</a>
						</li>
						{% endif %}
						<li><hr class="dropdown-divider"></li>
					</ul>
				</li>
				{% endif %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color: black;" data-bs-toggle="dropdown" href="{% url 'productos' %}" role="button" aria-expanded="true">Productos</a>
					<ul class="dropdown-menu">
					<li><a class="dropdown-item" href="{% url 'productos' %}">Romance</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="{% url 'fantasia' %}">Fantasía</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="{% url 'RomanceClasico' %}">Romance Clasico</a></li>
					
					</ul>
				</li>
				{% if user.is_authenticated %}
				<li>
					<a class="nav-link" style="color: black;" href="#">{{ user.username }}
					</a>
				</li>

				<li>
					<a class="nav-link" style="color: black;" href="{% url 'logout' %}">Cerrar Session</a>
				</li>
				

				{% else %}
				<li>
					<a class="nav-link" style="color: black;" href="{% url 'login' %}">Iniciar Sesion</a>
				</li>
				<li>
					<a class="nav-link" style="color: black;" href="{% url 'registro' %}">Registrate</a>
				</li>
				{% endif %}
			
				
				
			</ul>
			</section>
    <!-- Productos romance clasico -->

    {% load humanize %}
    <!-- productos -->
    <div class="produ">
      {% for p in libros %}
        <div class="card" style="width: 23rem;">
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="">
            {% endif %}
            <div class="card-body">
              <h5>{{p.autor | capfirst}}</h5>
              <h2 class="card-title">{{p.nombre | title}}</h2>
              <h3>${{p.precio | intcomma}}
              </h3>

              <a href="{% url 'Add' producto_id=p.id %}" class="btn-btn-primary">Comprar</a>




            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container container-footer">
            <div class="menu-footer">
                <div class="contact-info">
                    <p class="title-footer">Información de Contacto</p>
                    <ul>
                        <li>
                            Dirección: 222 Viña del Mar, Chile 
                        </li>
                        <li>Teléfono: 33 747474</li>
                        <li>Celular: 55555300</li>
                        <li>EmaiL: Librosj&@gmail.com</li>
                    </ul>
                    <div class="social-icons">
                        <span class="facebook">
                            <i class="fa-brands fa-facebook-f"></i>
                        </span>
                        <span class="twitter">
                            <i class="fa-brands fa-twitter"></i>
                        </span>
                        <span class="youtube">
                            <i class="fa-brands fa-youtube"></i>
                        </span>
                        <span class="pinterest">
                            <i class="fa-brands fa-pinterest-p"></i>
                        </span>
                        <span class="instagram">
                            <i class="fa-brands fa-instagram"></i>
                        </span>
                    </div>
                </div>

                <div class="information">
                    <p class="title-footer">Información</p>
                    <ul>
                        <li><a href="#">Acerca de Nosotros</a></li>
                        <li><a href="#">Información Delivery</a></li>
                        <li><a href="#">Politicas de Privacidad</a></li>
                        <li><a href="#">Términos y condiciones</a></li>
                        <li><a href="#">Contactános</a></li>
                    </ul>
                </div>

                <div class="my-account">
                    <p class="title-footer">Mi cuenta</p>

                    <ul>
                        <li><a href="#">Mi cuenta</a></li>
                        <li><a href="#">Historial de ordenes</a></li>
                        <li><a href="#">Lista de deseos</a></li>
                        <li><a href="#">Boletín</a></li>
                        <li><a href="#">Reembolsos</a></li>
                    </ul>
                </div>

                <div class="newsletter">
                    <p class="title-footer">Boletín informativo</p>

                    <div class="content">
                        <p>
                            Suscríbete a nuestros boletines ahora y mantente al
                            día con nuevas colecciones y ofertas exclusivas.
                        </p>
                        <input type="email" placeholder="Ingresa el correo aquí...">
                        <button>Registrate</button>
                    </div>
                </div>
            </div>

            <div class="copyright">
                <p>
                    Desarrollado J&C &copy; 2023
                </p>

                <img src="images/payment.png" alt="Pagos">
            </div>
        </div>
    </footer>
    <button class="btn-scrolltop" id="btn_scrolltop">
        <i class="fas fa-chevron-up"></i>
      </button>
      <script>
        const btn_scrolltop = document.getElementById("btn_scrolltop")
          btn_scrolltop.addEventListener('click', () => {
            window.scrollTo(0, 0)
          })
    
        window.onscroll = () => {
          add_btn_scrolltop()
        }
    
        const add_btn_scrolltop = () => {
          if (window.scrollY < 300) {
            btn_scrolltop.classList.remove("btn-scrolltop-on")
          } else {
            btn_scrolltop.classList.add("btn-scrolltop-on")
          }
        }
      </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script
    src="https://kit.fontawesome.com/81581fb069.js"
    crossorigin="anonymous"
    ></script>

</body>
</html>

tienda/templates/tienda/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta
		name="viewport"
		content="width=device-width, initial-scale=1">
		<title>LibrosJ&C</title>
		<link rel="stylesheet" href="{% static 'css/styles.css'%}" >
		<link rel="stylesheet" href="{% static 'css/estilos.css'%}">
		<link rel="stylesheet" href="{% static 'css/productos.css'%}"/>
		<link rel="stylesheet" href="{% static 'css/nav.css'%}">
		<link rel="stylesheet" href="{% static 'css/nuevo.css'%}">
		<link rel="stylesheet" href="{% static 'css/carrusel.css'%}">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
		integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	  
	</head>


	<body>
		<!--comienzo del header-->
		<header>
			<div class="container-hero" >
				<div class="container hero">
					<div class="customer-support">
						<i class="fa-solid fa-headset"></i>
						<div class="content-customer-support">
							<span class="text">Soporte al cliente</span>
							<span class="number">123-456-7890</span>
						</div>
					</div>

					<div class="container-logo">
						<i class="books"></i>
						<h1 class="logo"><a href="#" > <img src="{% static 'images/LOGO (4).svg'%}" alt="" width="80" height="80"> </a></h1>
					</div>

					<div class="container-user">
						<a href="{% url 'Login' %}"><i class="fa-solid fa-user"></i></a>
						<a href="{% url 'carrito' %}"><i class="fa-solid fa-basket-shopping"></i></a>
						<div class="content-shopping-cart">
							<span class="link-carrito"></a> </span>
							<span class="number"></span>
						</div>
					</div>
				</div>
			</div>
		</header>
			<!-- fin del header -->


			<!--aqui comienza el nav-->
			<section class="nav-total">
			<ul class="nav nav-tabs" style="justify-content:center;">
				<li class="nav-item">
				<a class="nav-link"  style="color: black;"  aria-current="page" href="{% url 'Inicio' %}">Inicio</a>
				</li>
				
				
				<li class="nav-item">
				<a class="nav-link" style="color: black;" href="{% url 'Nosotros' %}">Nosotros</a>
				</li>
				
				{% if perms.tienda.add_libro %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color: black;" data-bs-toggle="dropdown" href="{% url 'productos' %}" role="button" aria-expanded="true">Administración</a>
					<ul class="dropdown-menu">
						{% if perms.tienda.add_libro %}
						<li class="nav-item">
							<a class="nav-link" style="color: black;" href="{% url 'agregar' %}">Agregar</a>
						</li>
						{% endif %}
						<li><hr class="dropdown-divider"></li>
						{% if perms.tienda.view_libro %}
						<li class="nav-item">
						<a class="nav-link" style="color: black;" href="{% url 'libroList' %}">Listar</a>
						</li>
						{% endif %}
						<li><hr class="dropdown-divider"></li>
					</ul>
				</li>
				{% endif %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" style="color: black;" data-bs-toggle="dropdown" href="{% url 'productos' %}" role="button" aria-expanded="true">Productos</a>
					<ul class="dropdown-menu">
					<li><a class="dropdown-item" href="{% url 'productos' %}">Romance</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="{% url 'fantasia' %}">Fantasía</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="{% url 'RomanceClasico' %}">Romance Clasico</a></li>
					
					</ul>
				</li>
				{% if user.is_authenticated %}
				<li>
					<a class="nav-link" style="color: black;" href="#">{{ user.username }}
					</a>
				</li>

				<li>
					<a class="nav-link" style="color: black;" href="{% url 'logout' %}">Cerrar Session</a>
				</li>
				

				{% else %}
				<li>
					<a class="nav-link" style="color: black;" href="{% url 'login' %}">Iniciar Sesion</a>
				</li>
				<li>
					<a class="nav-link" style="color: black;" href="{% url 'registro' %}">Registrate</a>
				</li>
				{% endif %}
			
				
				
			</ul>
			</section>


		<div id="contenido1">




            {% block contenido1 %}

            {% endblock %}





        </div>	







		<button class="btn-scrolltop" id="btn_scrolltop">
			<i class="fas fa-chevron-up"></i>
		  </button>
		  <script>
			const btn_scrolltop = document.getElementById("btn_scrolltop")
			  btn_scrolltop.addEventListener('click', () => {
				window.scrollTo(0, 0)
			  })
		
			window.onscroll = () => {
			  add_btn_scrolltop()
			}
		
			const add_btn_scrolltop = () => {
			  if (window.scrollY < 300) {
				btn_scrolltop.classList.remove("btn-scrolltop-on")
			  } else {
				btn_scrolltop.classList.add("btn-scrolltop-on")
			  }
			}
		  </script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
		<script
			src="https://kit.fontawesome.com/81581fb069.js"
			crossorigin="anonymous"
		></script>
		<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
		<script src="{% static './js/main.js'%}"></script>
	</body>
</html>

tienda/templates/tienda/carrito.html
{%extends 'tienda/base.html'%}

{% block contenido1 %}

{% load static %}


<div class="alert-alert-primary" role="alert">
  <table class="table table-hover" style="font-size: large;">
    <thead>
      <tr>
        <th scope="row" colspan="3" class="text-center">CARRITO</th>
      </tr>
      <tr>
        <th scope="col">NOMBRE</th>
        <th scope="col">PRECIO</th>
        <th scope="col">CANTIDAD</th>
      </tr>
    </thead>
    <tbody><br><br>
    {% if request.session.carrito.items %}
    {% for key, value in request.session.carrito.items %}
      <tr>
        <td>{{value.nombre}}</td>
        <td>{{value.precio}}</td>
        <td>{{value.acumulado}}
          <a href="{% url 'Add' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
          <a href="{% url 'Sub' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
        </td>
      </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">
            <div class="alert alert-danger text-center"> Sin Productos </div>
        </td>
    </tr>
    {% endif %}
      <tr>
        <th scope="row">Total:</th>
        <td colspan="2">$ {{total_carrito}}</td>
      </tr>
    </tbody>
  </table>
  <hr>
  </div>
  <div class="row text-center" >
      <div class="col-6"><a href="{% url 'CLS' %}" class="btn-btn-primary">Limpiar</a></div>
      <div class="col-6"><a href="#" class="btn-btn-primary ">Comprar</a></div>
  </div>

      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    </body>
    </html>
    








    {% endblock %}