tienda/urls.py
from django.urls import path 
from .views import AgregarAutor, Inicio, Nosotros,  Login, contactoList, productos, Registro, contacto, AgregarLibro, libroList, fantasia, RomanceClasico, modificarLibro, eliminarLibro,  registro, carrito



urlpatterns = [
    path('Inicio/', Inicio, name='Inicio'), 
    path('Nosotros/', Nosotros, name='Nosotros'),
    path('Login/', Login, name='Login'), 
    path('productos/', productos, name='productos'), 
    path('Registro/', Registro, name='Registro'), 
    path('contacto/', contacto, name='contacto'), 
    path('agregar-libro/', AgregarLibro, name='agregar'), 
    path('libroList/', libroList, name='libroList'), 
    path('fantasia/', fantasia, name='fantasia'), 
    path('RomanceClasico/', RomanceClasico, name='RomanceClasico'), 
    path('modificarLibro/<int:id>/', modificarLibro, name='modificarLibro'),

    path('eliminarLibro/<id>/', eliminarLibro, name='eliminarLibro'), 
    path('registro/', registro, name='registro'), 
    path('carrito/', carrito, name='carrito'),
    path('agregar-Autor/', AgregarAutor, name='agregarAutor'), 
    path('contactoList/', contactoList, name='contactoList'), 






]

tienda/models.py
from collections import UserList
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Autor(models.Model):
    idAutor = models.IntegerField()
    nombre = models.CharField(max_length=100)

    def __str__(selft):
        return selft.nombre
    
opciones_categoria = [
    [0, "Romance"],
    [1, "Fantasia"],
    [2, "Romance Clasico"]
]
    
class Libro(models.Model):
    isbn = models.IntegerField()
    nombre = models.CharField(max_length=400)
    precio = models.IntegerField()
    categoria = models.IntegerField(choices=opciones_categoria)
    nuevo = models.BooleanField()
    autor = models.ForeignKey(Autor, on_delete=models.PROTECT)
    imagen = models.ImageField(upload_to="Libros",null=True)

    def __str__(selft):
        return selft.nombre
    

tipoConsulta = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencia"],
    [3, "Felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=30)
    correo = models.EmailField()
    tipoConsulta = models.IntegerField(choices=tipoConsulta)
    mensaje = models.TextField()
    
    def __str__(selft):
        return selft.nombre
    




##modelo del carrito
class Carrito(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    elementos = models.ManyToManyField(Libro, through='ElementoCarrito')

    def __str__(self):
        return f"Carrito de {self.usuario.username}"    
    



class ElementoCarrito(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Libro, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Elemento del carrito {self.carrito} - Producto: {self.producto} - Cantidad: {self.cantidad}"
    
    
    def subtotal(self):
        return self.producto.precio * self.cantidad
    

tienda/templates/tienda/Libros/agregar.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/crud.css'%}">
    <link rel="stylesheet" href="{% static 'css/ncontacto.css'%}">
    <title>Editar Libros</title>
</head>
<body>
    <br>
    <br>
    
    <div class="row"  >
        <div class="col-12 col-md-6 offset-md-3">


                 <div class="card" >
                        <div class="card-body ">
                            <h2>Editar Libros</h2>

                        <hr>
             <form action="" class="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form|crispy}} 


                        <br>
                        <hr>
                        <div class="d-flex justify-content-end">
                            <button type="button"><a href="{% url 'Inicio' %}">Inicio</a></button>
                            &nbsp;
                            <button type="button"><a href="{% url 'agregarAutor' %}">Agregar Autor</a></button>
                            &nbsp;
                            <button type="button"><a href="{% url 'libroList' %}">Agregados</a></button>
                            &nbsp;
                            <button type="submit" id="Editar" class="btn btn-primary">Enviar</button>
                            
                        </div>
                    </form>
                    {{mensaje}}
                </div>
            </div>
            
            
        </div>
    </div>
    <br>
    <br>
</body>
</html>

tienda/templates/tienda/Libros/agregarAutor.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/crud.css'%}">
    <link rel="stylesheet" href="{% static 'css/ncontacto.css'%}">
    <title>Editar Libros</title>
</head>
<body>
    <br>
    <br>
    
    <div class="row"  >
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" >
                <div class="card-body ">
                    <h2>Editar Autor</h2>
                    <hr>
                    <form action="" class="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy}} 
                        <br>
                        <hr>
                        <div class="d-flex justify-content-end">
                            <button type="button"><a href="{% url 'agregar' %}">Volver</a></button>
                            &nbsp;
                            <button type="button"><a href="{% url 'libroList' %}">Agregados</a></button>
                            &nbsp;
                            <button type="submit" id="Editar" class="btn btn-primary">Enviar</button>
                            
                        </div>
                    </form>
                    {{mensaje}}
                </div>
            </div>
            
            
        </div>
    </div>
    <br>
    <br>
</body>
</html>

tienda/templates/tienda/Libros/contactoList.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/crud.css' %}">
    
    <title>Listar Mensajes de Contacto</title>
</head>
<body>
    
    <br>
    <br>
    <div class="card">
        <div class="card-body">
            <h2>Lista de Mensajes de Contacto</h2>
            <hr>
            <table class="table table-striped table-hover table-responsive-sm">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Email</th>
                        <th scope="col">Mensaje</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contacto in contactos %}
                        <tr>
                            <td>{{ contacto.nombre }}</td>
                            <td>{{ contacto.email }}</td>
                            <td>{{ contacto.mensaje }}</td>
                            <td>
                                {% if perms.tienda.change_contacto %}
                                    <a href="{% url 'modificarContacto' contacto.id %}" class="btn btn-info btn-sm">Modificar</a>
                                {% endif %}
                                {% if perms.tienda.delete_contacto %}
                                    <a href="#" onclick="eliminarContacto({ contacto,id })" class="btn btn-danger btn-sm">Eliminar</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
   
    <!-- Otros scripts y estilos -->
    
    {% block js %}
        <script>
           function eliminarContacto(id) {
            Swal.fire({
                "title": "¿Estás seguro?",
                "text": "Esta acción no se puede deshacer",
                "icon": "question",
                "showCancelButton": true,
                "cancelButtonText": "No, Cancelar",
                "confirmButtonText": "Si, Eliminar",
                "reverseButtons": true,
                "confirmButtonColor": "#dc3545"
            })
            .then(function(result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminarContacto/" + id + "/"
                }
            })
           } 
        </script>

{% endblock %}

tienda/templates/tienda/Libros/listar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/crud.css'%}">
    
    <title>Listar Libros</title>
</head>
<body>
    
    <br>
    <br>
    <div class="card">
        <div class="card body">
            <h2>Lista de Libros</h2>
            <hr>
            <table class="table table-striped table-hover table-responsive-sm" id="libros">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ISBN</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Categoria</th>
                        <th scope="col">Autor</th>
                        
                        <th scope="col">Opciones</th>
                        
                    </tr>
                </thead>

                {% for lista in entity %}
                <tr>
                    <td>{{lista.isbn}}</td>
                    <td>{{lista.nombre}}</td>
                    <td>{{lista.precio}}</td>
                    <td>{{lista.categoria}}</td>
                    <td>{{lista.autor}}</td>
                    
                    <td>
                        {% if perms.tienda.change_libro %}
                        <a href="{% url 'modificarLibro' lista.id %}" class="btn btn-info btn-sm">Modificar</a>
                        {% endif %}
                        {% if perms.tienda.delate_libro %}
                        <a href="#" onclick="eliminarLibro({{ lista.id }})" class="btn btn-danger btn-sm">Eliminar</a>
                        {% endif %}
                    </td>
                
                </tr>
                {% endfor %}
            </table>
            <hr>
            
            <div>
                {% include 'tienda/paginator.html' %}
            </div>
            

        </div>
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function(){
            $("#idMensajes").delay(2000).fadeOut("slow");
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
                {% for m in messages%}
                    <script>
                        Swal.fire({
                            "title": "Felicitaciones",
                            "text": "{{m}}",
                            "icon": "success"
                        })
                    </script>
                {% endfor %}
    {% endif %}
    {% block js%}
        <script>
           function eliminarLibro(id) {
            Swal.fire({
                "title": "¿Estas Seguro?",
                "text": "Esta Accion no se puede deshacer",
                "icon": "question",
                "showCancelButton":true,
                "cancelButtonText":"No, Cancelar",
                "confirmButtonText":"Si, Eliminar",
                "reverseButtons":true,
                "confirmButtonColor": "#dc3545"

            })
            .then(function(result) {
                if(result.isConfirmed) {
                    window.location.href = "/eliminarLibro/"+id+"/"
                }
            })
            
           } 
        </script>
    {% endblock %}
    
</body>
</html>

tienda/templates/tienda/Libros/modificar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load crispy_forms_tags %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/crud.css'%}">
    <link rel="stylesheet" href="{% static 'css/ncontacto.css'%}">
    <title>Agregar Libros</title>
</head>
<body>
    <br>
    <br>
    <div class="row"  >
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card" >
                <div class="card-body ">
                    <h2>Modificar Libros</h2>
                    <hr>
                    <form action="" class="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy  }} 
                        <br>
                        <hr>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <button type="submit" id="btnEnviar" class="btn btn-primary">enviar</button>
                            &nbsp;
                            
                        </div>
                    </form>
                    {{mensaje}}
                </div>
            </div>
            
            
        </div>
    </div>
    <br>
    <br>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>